#! /bin/sh
#
# Author: Alessandro de Oliveira Faria <cabelo@opensuse.org>
#
# /etc/init.d/opencertiface
#   and its symbolic link
# /usr/sbin/opencertiface
#
### BEGIN INIT INFO
# Provides: opencertiface
# Required-Start: 
# X-UnitedLinux-Should-Start: 
# Required-Stop:
# Default-Start:  3 5
# Default-Stop:
# Description: People Profile 
### END INIT INFO

_PORT="8081"
_NAME="openCertiface"
_BIN="/usr/sbin/opencertiface"
PID_FILE="/var/run/opencertiface.pid"
PID_FILEGuardian="/var/run/opencertifaceGuardian.pid"


. /etc/rc.status
rc_reset

# Check for missing binary
if [ ! -x ${_BIN} ]; then
	echo -n "$_NAME daemon, ${_BIN} is not installed. "
	rc_status -s
	exit 5
fi


# be extra carefull cause connection fail if TMPDIR is not writeable
export TMPDIR="/var/tmp"

case "$1" in
	start)
		echo -n "Starting $_NAME daemon "
		checkproc -p ${PID_FILE} ${_BIN} 
		case $? in
			0) echo -n "- Warning: daemon already running. " ;;
			1) echo -n "- Warning: ${PID_FILE} exists. " ;;
		esac
		startproc -p ${PID_FILE} ${_BIN} ${_PORT}
# > /dev/null 
		rc_status -v
		;;
	stop)
		echo -n "Shutting $_NAME daemon "
		checkproc -p ${PID_FILE} ${_BIN} || \
			echo -n " Warning: daemon not running. "
		killproc -p ${PID_FILEGuardian} ${_BIN}
		killproc -p ${PID_FILE} ${_BIN}
		rc_status -v
		;;
	try-restart|condrestart)
		if test "$1" = "condrestart"; then
			echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
		fi
		$0 status
		if test $? = 0; then
			$0 restart
		else 
			rc_reset
		fi
		rc_status
		;;
	restart)
		$0 stop
		$0 start
		rc_status
		;;
	force-reload)
		$0 reload
		rc_status
		;;
	reload)
		echo -n "Reloading $_NAME daemon "
		checkproc -p ${PID_FILE} ${_BIN} || \
			echo -n " Warning: daemon not running. "
		killproc -p ${PID_FILE} -HUP ${_BIN}
		rc_status -v
		;;
	status)
		echo -n "Checking for $_NAME daemon "
		checkproc -p ${PID_FILE} ${_BIN}
		rc_status -v
		;;
	probe)
		test -nt ${PID_FILE} && echo reload
		;;
	*)
		echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
		exit 1
		;;
esac
rc_exit

